// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mini_projet_net.Models;

#nullable disable

namespace Mini_projet_net.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240516014131_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Mini_projet_net.Models.Article", b =>
                {
                    b.Property<int>("articleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("articleId"), 1L, 1);

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Prix")
                        .HasColumnType("real");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<int>("categorieId")
                        .HasColumnType("int");

                    b.HasKey("articleId");

                    b.HasIndex("categorieId");

                    b.ToTable("articles");
                });

            modelBuilder.Entity("Mini_projet_net.Models.Categorie", b =>
                {
                    b.Property<int>("categorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categorieId"), 1L, 1);

                    b.Property<string>("Namecategorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("categorieId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Mini_projet_net.Models.Article", b =>
                {
                    b.HasOne("Mini_projet_net.Models.Categorie", "categorie")
                        .WithMany("articles")
                        .HasForeignKey("categorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categorie");
                });

            modelBuilder.Entity("Mini_projet_net.Models.Categorie", b =>
                {
                    b.Navigation("articles");
                });
#pragma warning restore 612, 618
        }
    }
}
